
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Personality_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(454, 374)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 451, 371))
        self.groupBox.setObjectName("groupBox")
        self.Cancel = QtWidgets.QPushButton(self.groupBox)
        self.Cancel.setGeometry(QtCore.QRect(10, 340, 114, 32))
        self.Cancel.setObjectName("Cancel")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 92, 311))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19name = QtWidgets.QLabel(self.widget)
        self.label_19name.setObjectName("label_19name")
        self.verticalLayout.addWidget(self.label_19name)
        self.label_4s_name = QtWidgets.QLabel(self.widget)
        self.label_4s_name.setObjectName("label_4s_name")
        self.verticalLayout.addWidget(self.label_4s_name)
        self.labelf_name = QtWidgets.QLabel(self.widget)
        self.labelf_name.setObjectName("labelf_name")
        self.verticalLayout.addWidget(self.labelf_name)
        self.label_17student_id = QtWidgets.QLabel(self.widget)
        self.label_17student_id.setObjectName("label_17student_id")
        self.verticalLayout.addWidget(self.label_17student_id)
        self.label_21birth_city = QtWidgets.QLabel(self.widget)
        self.label_21birth_city.setObjectName("label_21birth_city")
        self.verticalLayout.addWidget(self.label_21birth_city)
        self.label_13country = QtWidgets.QLabel(self.widget)
        self.label_13country.setObjectName("label_13country")
        self.verticalLayout.addWidget(self.label_13country)
        self.label_11birht_date = QtWidgets.QLabel(self.widget)
        self.label_11birht_date.setObjectName("label_11birht_date")
        self.verticalLayout.addWidget(self.label_11birht_date)
        self.label_23email_address = QtWidgets.QLabel(self.widget)
        self.label_23email_address.setObjectName("label_23email_address")
        self.verticalLayout.addWidget(self.label_23email_address)
        self.label_15Phone_number = QtWidgets.QLabel(self.widget)
        self.label_15Phone_number.setObjectName("label_15Phone_number")
        self.verticalLayout.addWidget(self.label_15Phone_number)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(120, 20, 301, 311))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditName = QtWidgets.QLineEdit(self.widget1)
        self.lineEditName.setReadOnly(True)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_2.addWidget(self.lineEditName)
        self.lineEdit_3LastName = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3LastName.setReadOnly(True)
        self.lineEdit_3LastName.setObjectName("lineEdit_3LastName")
        self.verticalLayout_2.addWidget(self.lineEdit_3LastName)
        self.lineEdit_4FatherName = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4FatherName.setReadOnly(True)
        self.lineEdit_4FatherName.setObjectName("lineEdit_4FatherName")
        self.verticalLayout_2.addWidget(self.lineEdit_4FatherName)
        self.lineEdit_6StudentID = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_6StudentID.setReadOnly(True)
        self.lineEdit_6StudentID.setObjectName("lineEdit_6StudentID")
        self.verticalLayout_2.addWidget(self.lineEdit_6StudentID)
        self.lineEdit_7BirthCity = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_7BirthCity.setReadOnly(True)
        self.lineEdit_7BirthCity.setObjectName("lineEdit_7BirthCity")
        self.verticalLayout_2.addWidget(self.lineEdit_7BirthCity)
        self.lineEdit_8Country = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_8Country.setReadOnly(True)
        self.lineEdit_8Country.setObjectName("lineEdit_8Country")
        self.verticalLayout_2.addWidget(self.lineEdit_8Country)
        self.lineEdit_9BirthDate = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_9BirthDate.setReadOnly(True)
        self.lineEdit_9BirthDate.setObjectName("lineEdit_9BirthDate")
        self.verticalLayout_2.addWidget(self.lineEdit_9BirthDate)
        self.lineEdit_10EmailAddress = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_10EmailAddress.setReadOnly(True)
        self.lineEdit_10EmailAddress.setObjectName("lineEdit_10EmailAddress")
        self.verticalLayout_2.addWidget(self.lineEdit_10EmailAddress)
        self.lineEdit_11PhoneNumber = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_11PhoneNumber.setReadOnly(True)
        self.lineEdit_11PhoneNumber.setObjectName("lineEdit_11PhoneNumber")
        self.verticalLayout_2.addWidget(self.lineEdit_11PhoneNumber)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "                            Student Personality"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.label_19name.setText(_translate("Dialog", "Name"))
        self.label_4s_name.setText(_translate("Dialog", "Last name"))
        self.labelf_name.setText(_translate("Dialog", "Father name"))
        self.label_17student_id.setText(_translate("Dialog", "Student ID "))
        self.label_21birth_city.setText(_translate("Dialog", "Birth city"))
        self.label_13country.setText(_translate("Dialog", "Country"))
        self.label_11birht_date.setText(_translate("Dialog", "Birth date"))
        self.label_23email_address.setText(_translate("Dialog", "Email address"))
        self.label_15Phone_number.setText(_translate("Dialog", "Phone number"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.label_25.setText(_translate("Dialog", "TextLabel"))



if __name__=='__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    Dialog=QtWidgets.QDialog()
    v1=Ui_Personality_Dialog()
    v1.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

